spin_manifest_version = "1"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = "Short link redirector"
name = "redirect"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "api"
source = "api/target/wasm32-wasi/release/api.wasm"
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "client"
files = [ {source = "client", destination = "/" } ]
[component.trigger]
route = "/admin/..."

[[component]]
id = "redirect"
source = "redirect/target/wasm32-wasi/release/redirect.wasm"
key_value_stores = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "redirect"
watch = ["src/**/*.rs", "Cargo.toml", "spin.toml"]
